package one.jpro.platform.aidocs.core;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates a SKILL.md file that describes the AI docs file structure
 * so AI coding agents know the documentation system exists and how to use it.
 *
 * The template is loaded from the classpath resource {@code SKILL.md}, which is
 * copied from the project root during the build. The placeholder path
 * {@code build/ai-docs} in the template is replaced with the actual output directory.
 */
public class SkillGenerator {

    private static final String DEFAULT_DOCS_DIR = "build/ai-docs";
    private static final String DEFAULT_TOOL_NAME = "Gradle";
    private static final String DEFAULT_COLLECT_COMMAND = "gradle collectDocs";
    private static final String TEMPLATE_RESOURCE = "SKILL.md";

    /** Marker identifying a generated file; without it an existing file is treated as user-owned. */
    static final String GENERATED_MARKER = "Generated by the AI Docs plugin";

    /**
     * Generates a SKILL.md file at the given path. An existing file is only overwritten
     * if it still contains the generated-file marker — a user-modified file is left untouched.
     *
     * @param skillPath path to write the SKILL.md
     * @param docsOutputDir the relative path to the docs output directory (e.g. "build/ai-docs")
     * @param buildTool the build tool whose collect command should be referenced
     * @return true if the file was written, false if a user-owned file was left untouched
     */
    public static boolean generate(Path skillPath, String docsOutputDir, BuildTool buildTool) throws IOException {
        if (Files.exists(skillPath) && !Files.readString(skillPath).contains(GENERATED_MARKER)) {
            return false;
        }
        String content = generate(docsOutputDir, buildTool);
        Files.createDirectories(skillPath.getParent());
        Files.writeString(skillPath, content);
        return true;
    }

    /**
     * Generates SKILL.md content by loading the template and substituting the
     * output directory and build tool references.
     */
    static String generate(String docsOutputDir, BuildTool buildTool) throws IOException {
        String template = loadTemplate();
        return template
                .replace(DEFAULT_COLLECT_COMMAND, buildTool.collectCommand())
                .replace(DEFAULT_TOOL_NAME, buildTool.displayName())
                .replace(DEFAULT_DOCS_DIR, docsOutputDir);
    }

    private static String loadTemplate() throws IOException {
        try (InputStream is = SkillGenerator.class.getResourceAsStream(TEMPLATE_RESOURCE)) {
            if (is == null) {
                throw new IOException("SKILL.md template not found on classpath");
            }
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
